// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddBookmarkTag(ctx context.Context, arg AddBookmarkTagParams) error
	AddTaskTag(ctx context.Context, arg AddTaskTagParams) error
	CreateBookmark(ctx context.Context, arg CreateBookmarkParams) (Bookmark, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) error
	DeleteTask(ctx context.Context, arg DeleteTaskParams) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetBookmarkByID(ctx context.Context, arg GetBookmarkByIDParams) (Bookmark, error)
	GetBookmarksByTag(ctx context.Context, arg GetBookmarksByTagParams) ([]Bookmark, error)
	GetBookmarksByUser(ctx context.Context, arg GetBookmarksByUserParams) ([]Bookmark, error)
	GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (Task, error)
	GetTasksByStatus(ctx context.Context, arg GetTasksByStatusParams) ([]Task, error)
	GetTasksByTag(ctx context.Context, arg GetTasksByTagParams) ([]Task, error)
	GetTasksByUser(ctx context.Context, arg GetTasksByUserParams) ([]Task, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	RemoveBookmarkTag(ctx context.Context, arg RemoveBookmarkTagParams) error
	RemoveTaskTag(ctx context.Context, arg RemoveTaskTagParams) error
	SearchBookmarks(ctx context.Context, arg SearchBookmarksParams) ([]Bookmark, error)
	SearchTasks(ctx context.Context, arg SearchTasksParams) ([]Task, error)
	UpdateBookmark(ctx context.Context, arg UpdateBookmarkParams) (Bookmark, error)
	UpdateLastLogin(ctx context.Context, id pgtype.UUID) error
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
}

var _ Querier = (*Queries)(nil)
