package main

import (
	"log"
	"os"
	"time"

	"github.com/trackeep/backend/config"
	"github.com/trackeep/backend/models"
	"golang.org/x/crypto/bcrypt"
)

// SeedData creates initial data for testing
func SeedData() {
	// Only seed data if demo mode is enabled
	if os.Getenv("VITE_DEMO_MODE") != "true" {
		log.Println("Demo mode disabled, skipping seed data")
		return
	}

	db := config.GetDB()
	if db == nil {
		log.Println("Database not initialized, skipping seed data")
		return
	}

	// Check if demo user already exists
	demoEmail := os.Getenv("VITE_DEMO_USER_EMAIL")
	if demoEmail == "" {
		demoEmail = "demo@trackeep.com"
	}

	var existingUser models.User
	if err := db.Where("email = ?", demoEmail).First(&existingUser).Error; err != nil {
		// Create demo user with proper password hashing
		hashedPassword, err := bcrypt.GenerateFromPassword([]byte("demo123"), bcrypt.DefaultCost)
		if err != nil {
			log.Printf("Failed to hash demo password: %v", err)
			return
		}

		user := models.User{
			Email:    demoEmail,
			Username: "demo",
			Password: string(hashedPassword),
			FullName: "Demo User",
			Role:     "admin", // Make demo user an admin for testing
			Theme:    "dark",
		}

		if err := db.Create(&user).Error; err != nil {
			log.Printf("Failed to create demo user: %v", err)
			return
		}
		existingUser = user
		log.Println("Created new demo user")
	} else {
		log.Println("Demo user already exists, creating demo data...")
	}

	// Create some demo tags
	tags := []models.Tag{
		{Name: "development", Color: "#39b9ff", UserID: existingUser.ID},
		{Name: "learning", Color: "#ff6b6b", UserID: existingUser.ID},
		{Name: "productivity", Color: "#51cf66", UserID: existingUser.ID},
		{Name: "golang", Color: "#845ef7", UserID: existingUser.ID},
		{Name: "javascript", Color: "#f76707", UserID: existingUser.ID},
		{Name: "documentation", Color: "#339af0", UserID: existingUser.ID},
		{Name: "tools", Color: "#20c997", UserID: existingUser.ID},
	}

	for _, tag := range tags {
		if err := db.Where("name = ? AND user_id = ?", tag.Name, tag.UserID).FirstOrCreate(&tag).Error; err != nil {
			log.Printf("Failed to create tag %s: %v", tag.Name, err)
		}
	}

	// Create some demo bookmarks
	bookmarks := []models.Bookmark{
		{
			UserID:      existingUser.ID,
			Title:       "Golang Official Documentation",
			URL:         "https://golang.org/doc/",
			Description: "Official Go programming language documentation",
			IsRead:      false,
			IsFavorite:  true,
		},
		{
			UserID:      existingUser.ID,
			Title:       "SolidJS Documentation",
			URL:         "https://www.solidjs.com/docs",
			Description: "Reactive JavaScript library documentation",
			IsRead:      true,
			IsFavorite:  false,
		},
		{
			UserID:      existingUser.ID,
			Title:       "Gin Web Framework",
			URL:         "https://gin-gonic.com/",
			Description: "HTTP web framework written in Go",
			IsRead:      false,
			IsFavorite:  true,
		},
		{
			UserID:      existingUser.ID,
			Title:       "GitHub",
			URL:         "https://github.com",
			Description: "Where the world builds software",
			IsRead:      false,
			IsFavorite:  true,
		},
		{
			UserID:      existingUser.ID,
			Title:       "Stack Overflow",
			URL:         "https://stackoverflow.com",
			Description: "Where developers learn, share, & build careers",
			IsRead:      true,
			IsFavorite:  false,
		},
	}

	for _, bookmark := range bookmarks {
		if err := db.Where("url = ? AND user_id = ?", bookmark.URL, bookmark.UserID).FirstOrCreate(&bookmark).Error; err != nil {
			log.Printf("Failed to create bookmark %s: %v", bookmark.Title, err)
		}
	}

	// Create some demo tasks
	tasks := []models.Task{
		{
			UserID:   existingUser.ID,
			Title:    "Complete Trackeep backend API",
			Status:   models.TaskStatusInProgress,
			Priority: models.TaskPriorityHigh,
			Progress: 75,
		},
		{
			UserID:   existingUser.ID,
			Title:    "Implement authentication system",
			Status:   models.TaskStatusCompleted,
			Priority: models.TaskPriorityHigh,
			Progress: 100,
		},
		{
			UserID:   existingUser.ID,
			Title:    "Add file upload functionality",
			Status:   models.TaskStatusPending,
			Priority: models.TaskPriorityMedium,
			Progress: 0,
		},
		{
			UserID:   existingUser.ID,
			Title:    "Write unit tests for API endpoints",
			Status:   models.TaskStatusPending,
			Priority: models.TaskPriorityLow,
			Progress: 0,
		},
		{
			UserID:   existingUser.ID,
			Title:    "Review and optimize database queries",
			Status:   models.TaskStatusPending,
			Priority: models.TaskPriorityMedium,
			Progress: 25,
		},
	}

	for _, task := range tasks {
		if err := db.Where("title = ? AND user_id = ?", task.Title, task.UserID).FirstOrCreate(&task).Error; err != nil {
			log.Printf("Failed to create task %s: %v", task.Title, err)
		}
	}

	// Create some demo notes
	notes := []models.Note{
		{
			UserID:      existingUser.ID,
			Title:       "Trackeep Project Notes",
			Content:     "# Trackeep Project\n\nA self-hosted productivity and knowledge hub built with Go backend and SolidJS frontend.\n\n## Features\n- Bookmark management\n- Task tracking\n- Note taking\n- File uploads\n- Authentication system",
			ContentType: "markdown",
			IsPinned:    true,
		},
		{
			UserID:      existingUser.ID,
			Title:       "API Design Principles",
			Content:     "## RESTful API Design\n\n- Use proper HTTP methods\n- Implement proper error handling\n- Add authentication and authorization\n- Provide clear documentation\n- Version the API",
			ContentType: "markdown",
			IsPinned:    false,
		},
		{
			UserID:      existingUser.ID,
			Title:       "Development Workflow",
			Content:     "## Git Workflow\n\n1. Create feature branch\n2. Make changes and commit\n3. Test thoroughly\n4. Create pull request\n5. Code review\n6. Merge to main",
			ContentType: "markdown",
			IsPinned:    false,
		},
	}

	for _, note := range notes {
		if err := db.Where("title = ? AND user_id = ?", note.Title, note.UserID).FirstOrCreate(&note).Error; err != nil {
			log.Printf("Failed to create note %s: %v", note.Title, err)
		}
	}

	// Create some demo time entries
	now := time.Now()
	timeEntries := []models.TimeEntry{
		{
			UserID:      existingUser.ID,
			Description: "Working on Trackeep backend API",
			StartTime:   now.Add(-2 * time.Hour),
			EndTime:     &[]time.Time{now.Add(-1 * time.Hour)}[0],
			Duration:    &[]int{3600}[0], // 1 hour
			Billable:    true,
			HourlyRate:  &[]float64{75.0}[0],
			IsRunning:   false,
			Source:      "manual",
		},
		{
			UserID:      existingUser.ID,
			Description: "Review and optimize database queries",
			StartTime:   now.Add(-4 * time.Hour),
			EndTime:     &[]time.Time{now.Add(-2 * time.Hour)}[0],
			Duration:    &[]int{7200}[0], // 2 hours
			Billable:    true,
			HourlyRate:  &[]float64{75.0}[0],
			IsRunning:   false,
			Source:      "manual",
		},
		{
			UserID:      existingUser.ID,
			Description: "Write unit tests for API endpoints",
			StartTime:   now.Add(-30 * time.Minute),
			Duration:    &[]int{1800}[0], // 30 minutes
			Billable:    false,
			IsRunning:   true,
			Source:      "manual",
		},
	}

	for _, timeEntry := range timeEntries {
		if err := db.Where("description = ? AND user_id = ?", timeEntry.Description, timeEntry.UserID).FirstOrCreate(&timeEntry).Error; err != nil {
			log.Printf("Failed to create time entry %s: %v", timeEntry.Description, err)
		}
	}

	// Create sample learning paths
	learningPaths := []models.LearningPath{
		{
			CreatorID:   existingUser.ID,
			Title:       "Complete Web Development with JavaScript",
			Description: "Learn modern web development from scratch with JavaScript, React, Node.js, and more.",
			Category:    "web-development",
			Difficulty:  "beginner",
			Duration:    "12 weeks",
			IsPublished: true,
			IsFeatured:  true,
			Thumbnail:   "/images/learning-paths/web-dev.jpg",
		},
		{
			CreatorID:   existingUser.ID,
			Title:       "Python for Data Science",
			Description: "Master Python programming and data science libraries like pandas, numpy, and scikit-learn.",
			Category:    "data-science",
			Difficulty:  "intermediate",
			Duration:    "8 weeks",
			IsPublished: true,
			IsFeatured:  true,
			Thumbnail:   "/images/learning-paths/python-data.jpg",
		},
		{
			CreatorID:   existingUser.ID,
			Title:       "Go Backend Development",
			Description: "Learn Go programming language and build scalable backend applications and APIs.",
			Category:    "programming",
			Difficulty:  "intermediate",
			Duration:    "10 weeks",
			IsPublished: true,
			IsFeatured:  false,
			Thumbnail:   "/images/learning-paths/go-backend.jpg",
		},
		{
			CreatorID:   existingUser.ID,
			Title:       "Cybersecurity Fundamentals",
			Description: "Introduction to cybersecurity concepts, ethical hacking, and security best practices.",
			Category:    "cybersecurity",
			Difficulty:  "beginner",
			Duration:    "6 weeks",
			IsPublished: true,
			IsFeatured:  false,
			Thumbnail:   "/images/learning-paths/cybersecurity.jpg",
		},
		{
			CreatorID:   existingUser.ID,
			Title:       "Mobile App Development with React Native",
			Description: "Build cross-platform mobile applications for iOS and Android using React Native.",
			Category:    "mobile-development",
			Difficulty:  "intermediate",
			Duration:    "8 weeks",
			IsPublished: true,
			IsFeatured:  false,
			Thumbnail:   "/images/learning-paths/react-native.jpg",
		},
		// Popular Programming Language Career Paths
		{
			CreatorID:   existingUser.ID,
			Title:       "JavaScript Mastery: From Basics to Advanced",
			Description: "Become a JavaScript expert covering ES6+, async programming, DOM manipulation, and modern frameworks.",
			Category:    "programming",
			Difficulty:  "beginner",
			Duration:    "10 weeks",
			IsPublished: true,
			IsFeatured:  true,
			Thumbnail:   "/images/learning-paths/javascript.jpg",
		},
		{
			CreatorID:   existingUser.ID,
			Title:       "TypeScript Professional Development",
			Description: "Master TypeScript for building type-safe applications with advanced patterns and best practices.",
			Category:    "programming",
			Difficulty:  "intermediate",
			Duration:    "6 weeks",
			IsPublished: true,
			IsFeatured:  true,
			Thumbnail:   "/images/learning-paths/typescript.jpg",
		},
		{
			CreatorID:   existingUser.ID,
			Title:       "Python Programming Complete Course",
			Description: "Learn Python from scratch with OOP, data structures, algorithms, and real-world applications.",
			Category:    "programming",
			Difficulty:  "beginner",
			Duration:    "12 weeks",
			IsPublished: true,
			IsFeatured:  true,
			Thumbnail:   "/images/learning-paths/python.jpg",
		},
		{
			CreatorID:   existingUser.ID,
			Title:       "Java Enterprise Development",
			Description: "Build enterprise applications with Java, Spring Boot, microservices, and cloud deployment.",
			Category:    "programming",
			Difficulty:  "intermediate",
			Duration:    "14 weeks",
			IsPublished: true,
			IsFeatured:  false,
			Thumbnail:   "/images/learning-paths/java.jpg",
		},
		{
			CreatorID:   existingUser.ID,
			Title:       "C# and .NET Development",
			Description: "Master C# programming and .NET framework for building Windows, web, and cloud applications.",
			Category:    "programming",
			Difficulty:  "intermediate",
			Duration:    "12 weeks",
			IsPublished: true,
			IsFeatured:  false,
			Thumbnail:   "/images/learning-paths/csharp.jpg",
		},
		{
			CreatorID:   existingUser.ID,
			Title:       "Rust Systems Programming",
			Description: "Learn Rust for systems programming, memory safety, and high-performance applications.",
			Category:    "programming",
			Difficulty:  "advanced",
			Duration:    "16 weeks",
			IsPublished: true,
			IsFeatured:  false,
			Thumbnail:   "/images/learning-paths/rust.jpg",
		},
		{
			CreatorID:   existingUser.ID,
			Title:       "C++ Game Development",
			Description: "Master C++ for game development with Unreal Engine, graphics programming, and performance optimization.",
			Category:    "programming",
			Difficulty:  "advanced",
			Duration:    "18 weeks",
			IsPublished: true,
			IsFeatured:  false,
			Thumbnail:   "/images/learning-paths/cpp.jpg",
		},
		{
			CreatorID:   existingUser.ID,
			Title:       "PHP Full-Stack Development",
			Description: "Build dynamic web applications with PHP, Laravel, MySQL, and modern frontend frameworks.",
			Category:    "programming",
			Difficulty:  "beginner",
			Duration:    "10 weeks",
			IsPublished: true,
			IsFeatured:  false,
			Thumbnail:   "/images/learning-paths/php.jpg",
		},
		{
			CreatorID:   existingUser.ID,
			Title:       "Ruby on Rails Development",
			Description: "Learn Ruby and Rails framework for rapid web application development with best practices.",
			Category:    "programming",
			Difficulty:  "intermediate",
			Duration:    "8 weeks",
			IsPublished: true,
			IsFeatured:  false,
			Thumbnail:   "/images/learning-paths/ruby.jpg",
		},
		{
			CreatorID:   existingUser.ID,
			Title:       "Swift iOS Development",
			Description: "Create native iOS applications with Swift, SwiftUI, and modern iOS development practices.",
			Category:    "mobile-development",
			Difficulty:  "intermediate",
			Duration:    "12 weeks",
			IsPublished: true,
			IsFeatured:  false,
			Thumbnail:   "/images/learning-paths/swift.jpg",
		},
		{
			CreatorID:   existingUser.ID,
			Title:       "Kotlin Android Development",
			Description: "Build modern Android applications with Kotlin, Jetpack Compose, and Android architecture patterns.",
			Category:    "mobile-development",
			Difficulty:  "intermediate",
			Duration:    "12 weeks",
			IsPublished: true,
			IsFeatured:  false,
			Thumbnail:   "/images/learning-paths/kotlin.jpg",
		},
		{
			CreatorID:   existingUser.ID,
			Title:       "SQL Database Mastery",
			Description: "Master SQL, database design, optimization, and advanced query techniques for data management.",
			Category:    "database",
			Difficulty:  "intermediate",
			Duration:    "8 weeks",
			IsPublished: true,
			IsFeatured:  false,
			Thumbnail:   "/images/learning-paths/sql.jpg",
		},
		{
			CreatorID:   existingUser.ID,
			Title:       "DevOps Engineering Career Path",
			Description: "Learn CI/CD, Docker, Kubernetes, cloud platforms, and infrastructure as code.",
			Category:    "devops",
			Difficulty:  "intermediate",
			Duration:    "12 weeks",
			IsPublished: true,
			IsFeatured:  false,
			Thumbnail:   "/images/learning-paths/devops.jpg",
		},
		// Advanced Cybersecurity Paths
		{
			CreatorID:   existingUser.ID,
			Title:       "Ethical Hacking and Penetration Testing",
			Description: "Master ethical hacking techniques, vulnerability assessment, and penetration testing methodologies.",
			Category:    "cybersecurity",
			Difficulty:  "advanced",
			Duration:    "16 weeks",
			IsPublished: true,
			IsFeatured:  true,
			Thumbnail:   "/images/learning-paths/ethical-hacking.jpg",
		},
		{
			CreatorID:   existingUser.ID,
			Title:       "Network Security and Defense",
			Description: "Learn network security, firewall configuration, intrusion detection, and security operations.",
			Category:    "cybersecurity",
			Difficulty:  "intermediate",
			Duration:    "12 weeks",
			IsPublished: true,
			IsFeatured:  false,
			Thumbnail:   "/images/learning-paths/network-security.jpg",
		},
		{
			CreatorID:   existingUser.ID,
			Title:       "Cloud Security Architecture",
			Description: "Master cloud security, AWS/Azure security services, compliance, and secure cloud architecture.",
			Category:    "cybersecurity",
			Difficulty:  "advanced",
			Duration:    "14 weeks",
			IsPublished: true,
			IsFeatured:  false,
			Thumbnail:   "/images/learning-paths/cloud-security.jpg",
		},
		{
			CreatorID:   existingUser.ID,
			Title:       "Digital Forensics and Incident Response",
			Description: "Learn digital forensics, incident response, malware analysis, and cybersecurity investigation.",
			Category:    "cybersecurity",
			Difficulty:  "advanced",
			Duration:    "18 weeks",
			IsPublished: true,
			IsFeatured:  false,
			Thumbnail:   "/images/learning-paths/digital-forensics.jpg",
		},
	}

	// Create ZTM Courses
	ztmCourses := []models.Course{
		// Programming Courses
		{
			Title:         "Complete Python Developer in 2026: Zero to Mastery",
			Description:   "Learn Python from scratch, get hired, and have fun along the way with the most up-to-date Python course on the web. Python is the entryway into the world of A.I., Cybersecurity, and many other high demand fields!",
			Slug:          "complete-python-developer-2026",
			URL:           "https://zerotomastery.io/courses/learn-python/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/2wqtcZLn5BirJ42EDfoair/95be1804195bb47acb392cec54eb551b/Complete_Python_Developer_Zero_to_Mastery.jpg",
			Instructor:    "Andrei Neagoie",
			Duration:      "32 Hours",
			LessonsCount:  346,
			Level:         "beginner",
			Category:      "programming",
			Price:         89.99,
			Rating:        4.7,
			StudentsCount: 250000,
			Prerequisites: []string{"Basic computer skills", "No programming experience required"},
			WhatYouLearn:  []string{"Python programming", "Data structures", "Algorithms", "OOP", "Web development with Python", "Automation"},
			Topics:        []string{"Python", "Programming", "Web Development", "Data Science", "Automation"},
			ToolsAndTech:  []string{"Python", "Django", "Flask", "NumPy", "Pandas", "Git"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "Master the Coding Interview: Data Structures + Algorithms",
			Description:   "The ultimate coding interview bootcamp to ace your coding interviews and land your dream job. Learn data structures & algorithms and the exact steps to take to get more interviews, more job offers, and a higher salary.",
			Slug:          "coding-interview-data-structures-algorithms",
			URL:           "https://zerotomastery.io/courses/learn-data-structures-and-algorithms/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/34oTrOaPCY3VKnubPKZCKv/a8eb7d89a56594d9d5acb91252b451b5/MTCI.png",
			Instructor:    "Andrei Neagoie",
			Duration:      "21 Hours",
			LessonsCount:  270,
			Level:         "intermediate",
			Category:      "programming",
			Price:         89.99,
			Rating:        4.8,
			StudentsCount: 180000,
			Prerequisites: []string{"Basic programming knowledge", "Understanding of basic data types"},
			WhatYouLearn:  []string{"Data structures", "Algorithms", "Problem solving", "Coding interviews", "Big O notation"},
			Topics:        []string{"Algorithms", "Data Structures", "Coding Interview", "Problem Solving"},
			ToolsAndTech:  []string{"Python", "JavaScript", "Data Structures", "Algorithms"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "Complete UI/UX Product Design Bootcamp: Zero to Mastery",
			Description:   "Go from beginner to hired as a UI/UX Designer this year! This is the only design bootcamp you need to learn and master web design, mobile design, Figma, UI & UX, and HTML + CSS.",
			Slug:          "ui-ux-product-design-bootcamp",
			URL:           "https://zerotomastery.io/courses/ui-ux-product-design-bootcamp/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/75XmCBS35kqsky2S2mtuoP/1f6b6aa94f921f14a833459d5ac8e82e/image.png",
			Instructor:    "Andrei Neagoie, Daniel Schifano",
			Duration:      "29 Hours",
			LessonsCount:  285,
			Level:         "beginner",
			Category:      "design",
			Price:         89.99,
			Rating:        4.6,
			StudentsCount: 95000,
			Prerequisites: []string{"No design experience required", "Computer with internet access"},
			WhatYouLearn:  []string{"UI Design", "UX Design", "Figma", "Web design", "Mobile design", "HTML & CSS"},
			Topics:        []string{"UI Design", "UX Design", "Figma", "Product Design", "Web Design"},
			ToolsAndTech:  []string{"Figma", "HTML", "CSS", "Adobe XD", "Sketch"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    false,
		},
		{
			Title:         "Advanced Ethical Hacking Bootcamp: Network Hacking & Security",
			Description:   "Take your ethical hacking skills to the next level. Learn how to exploit network vulnerabilities, bypass security measures, and craft your own exploits from scratch in this advanced network hacking course.",
			Slug:          "advanced-ethical-hacking-bootcamp",
			URL:           "https://zerotomastery.io/courses/advanced-ethical-hacking/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/6pQ2cKjY6Lcus7FbiGjpNL/6ac6f5608a36aac3759e16b2edfff067/Course_Thumbnail_-_Advanced_Ethical_Hacking_-_final2.jpg",
			Instructor:    "Aleksa Tamburkovski",
			Duration:      "7.5 Hours",
			LessonsCount:  76,
			Level:         "advanced",
			Category:      "cybersecurity",
			Price:         89.99,
			Rating:        4.8,
			StudentsCount: 45000,
			Prerequisites: []string{"Basic networking knowledge", "Linux fundamentals", "Previous ethical hacking experience"},
			WhatYouLearn:  []string{"Advanced network hacking", "Exploit development", "Security bypassing", "Penetration testing"},
			Topics:        []string{"Ethical Hacking", "Network Security", "Penetration Testing", "Exploit Development"},
			ToolsAndTech:  []string{"Metasploit", "Nmap", "Wireshark", "Burp Suite", "Kali Linux"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "CompTIA Security+ Certification Bootcamp",
			Description:   "Go from complete beginner to acing the globally-recognized CompTIA Security+ certification exam. You'll learn the latest cybersecurity best practices, techniques, and tools.",
			Slug:          "comptia-security-certification-bootcamp",
			URL:           "https://zerotomastery.io/courses/security-plus-boot-camp/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/2rvchxj7ZN43q1oF6mOy8T/19361b3478be905a14145c1c7994f6e4/Course_Thumbnail_-_CompTIA_Security__-_Normal_2.png",
			Instructor:    "Aleksa Tamburkovski",
			Duration:      "9 Hours",
			LessonsCount:  91,
			Level:         "beginner",
			Category:      "cybersecurity",
			Price:         89.99,
			Rating:        4.7,
			StudentsCount: 62000,
			Prerequisites: []string{"Basic IT knowledge", "No cybersecurity experience required"},
			WhatYouLearn:  []string{"CompTIA Security+", "Cybersecurity fundamentals", "Network security", "Risk management"},
			Topics:        []string{"CompTIA Security+", "Cybersecurity", "Network Security", "Risk Management"},
			ToolsAndTech:  []string{"Security Tools", "Network Monitoring", "SIEM", "Firewall Configuration"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    false,
		},
		{
			Title:         "Bash Scripting: Learn Shell Scripting",
			Description:   "Learn Bash Scripting from scratch, from an industry expert. You'll learn Shell Scripting fundamentals plus get the practice and experience to get hired as a DevOps Engineer, SysAdmin, or Network Engineer.",
			Slug:          "bash-scripting-shell-scripting",
			URL:           "https://zerotomastery.io/courses/learn-bash-scripting/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/395iMiqbPBUPQGGEluVUXT/ca0636cf2e4f182c5f5821386bcd02ee/Academy_3_Course_Thumbnail_-_Bash_Programming.png",
			Instructor:    "Andrei Dumitrescu",
			Duration:      "10 Hours",
			LessonsCount:  120,
			Level:         "intermediate",
			Category:      "devops",
			Price:         89.99,
			Rating:        4.6,
			StudentsCount: 38000,
			Prerequisites: []string{"Basic Linux knowledge", "Command line familiarity"},
			WhatYouLearn:  []string{"Bash scripting", "Shell programming", "Linux automation", "DevOps fundamentals"},
			Topics:        []string{"Bash", "Shell Scripting", "Linux", "DevOps", "Automation"},
			ToolsAndTech:  []string{"Bash", "Linux", "Shell", "Automation Tools", "Cron"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    false,
		},
		{
			Title:         "Advanced Excel Bootcamp: Data Analytics and Business Intelligence",
			Description:   "Become a Data Professional. You'll learn to master Excel's built-in power tools, including Power Query, Power Pivot Tables, Data Modeling, the DAX formula language, and so much more.",
			Slug:          "advanced-excel-bootcamp-data-analytics",
			URL:           "https://zerotomastery.io/courses/business-intelligence-course/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/2n1XBWfwVs3XyltFQ6ECzA/7c77783335cddcd14b40121417520d51/Course_Thumbnail_-_Business_Intelligence_with_Excel_-_Academy_2.png",
			Instructor:    "Travis Cuzick",
			Duration:      "9 Hours",
			LessonsCount:  84,
			Level:         "intermediate",
			Category:      "data",
			Price:         89.99,
			Rating:        4.5,
			StudentsCount: 28000,
			Prerequisites: []string{"Basic Excel knowledge", "Understanding of spreadsheets"},
			WhatYouLearn:  []string{"Advanced Excel", "Power Query", "Power Pivot", "DAX", "Data modeling"},
			Topics:        []string{"Excel", "Data Analytics", "Business Intelligence", "Power Query"},
			ToolsAndTech:  []string{"Excel", "Power Query", "Power Pivot", "DAX", "Power BI"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    false,
		},
		{
			Title:         "The AI Agents Bootcamp: Zero to Mastery",
			Description:   "Learn hands-on AI agent development using CrewAI, LangGraph, MCP, OpenAI and more. Build and deploy real multi-agent systems for automation, data workflows, and intelligent apps.",
			Slug:          "ai-agents-bootcamp",
			URL:           "https://zerotomastery.io/courses/ai-agents-bootcamp/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/1aWfPEIZchWyNbKoAi181o/43a1e23677077e353c4b2f83f8b25cb2/Course_Thumbnail_-_RAG_Bootcamp__5_.jpg",
			Instructor:    "Diogo Resende",
			Duration:      "7 Hours",
			LessonsCount:  83,
			Level:         "advanced",
			Category:      "ai",
			Price:         89.99,
			Rating:        4.7,
			StudentsCount: 15000,
			Prerequisites: []string{"Python programming", "Basic AI/ML knowledge", "API experience"},
			WhatYouLearn:  []string{"AI Agents", "CrewAI", "LangGraph", "Multi-agent systems", "OpenAI API"},
			Topics:        []string{"AI Agents", "CrewAI", "LangGraph", "Automation", "OpenAI"},
			ToolsAndTech:  []string{"Python", "CrewAI", "LangGraph", "OpenAI", "LangChain"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "Building AI Apps with the Gemini API",
			Description:   "Learn to use Google's Gemini API for building AI-powered applications. Plus you'll put your skills into action by building three projects using the Gemini API.",
			Slug:          "building-ai-apps-gemini-api",
			URL:           "https://zerotomastery.io/courses/learn-gemini-api/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/2EgntP5izs1HinJxcE93mL/f75a3875fec7c8464e181ee700aa2fcb/Blue__17_.png",
			Instructor:    "Andrei Dumitrescu",
			Duration:      "3.5 Hours",
			LessonsCount:  38,
			Level:         "intermediate",
			Category:      "ai",
			Price:         89.99,
			Rating:        4.6,
			StudentsCount: 8000,
			Prerequisites: []string{"Python programming", "Basic API knowledge", "Understanding of AI concepts"},
			WhatYouLearn:  []string{"Google Gemini API", "AI application development", "API integration", "Project building"},
			Topics:        []string{"Gemini API", "Google AI", "API Development", "AI Applications"},
			ToolsAndTech:  []string{"Python", "Google Gemini API", "REST APIs", "AI Integration"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    false,
		},
		{
			Title:         "Supercharged Code Editing with Vim and Neovim",
			Description:   "Learn to use Vim and Neovim with your favorite IDEs. You'll learn all the productivity-boosting shortcuts, macros, and techniques that will give you real mastery of code editing!",
			Slug:          "supercharged-code-editing-vim-neovim",
			URL:           "https://zerotomastery.io/courses/learn-neovim-and-vim/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/4CGgGrbErhZ0Ev35caINCg/ed1d7e9fdcffe844efbd9abd0237eeb7/Blue__16_.png",
			Instructor:    "Jayson Lennon",
			Duration:      "3 Hours",
			LessonsCount:  30,
			Level:         "intermediate",
			Category:      "tools",
			Price:         89.99,
			Rating:        4.8,
			StudentsCount: 12000,
			Prerequisites: []string{"Basic command line knowledge", "Text editor experience"},
			WhatYouLearn:  []string{"Vim", "Neovim", "Code editing", "Productivity", "IDE integration"},
			Topics:        []string{"Vim", "Neovim", "Text Editors", "Productivity", "Development Tools"},
			ToolsAndTech:  []string{"Vim", "Neovim", "IDE Plugins", "Command Line", "Text Editing"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    false,
		},
		{
			Title:         "Introduction to Inferential Statistics",
			Description:   "Learn real-world inferential statistics with Python including confidence intervals, hypothesis testing, and hands-on projects to build your data analysis skills from the ground up.",
			Slug:          "introduction-inferential-statistics",
			URL:           "https://zerotomastery.io/courses/learn-inferential-statistics/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/76EVNIyjQLoZBC3WcJHrO0/78f21c9e6ffd29cab9d543f266fa6c85/Blue.jpg",
			Instructor:    "Diogo Resende",
			Duration:      "9.5 Hours",
			LessonsCount:  131,
			Level:         "intermediate",
			Category:      "data",
			Price:         89.99,
			Rating:        4.5,
			StudentsCount: 9500,
			Prerequisites: []string{"Basic Python", "Understanding of basic statistics", "Data analysis interest"},
			WhatYouLearn:  []string{"Inferential statistics", "Hypothesis testing", "Confidence intervals", "Python for statistics"},
			Topics:        []string{"Statistics", "Data Analysis", "Hypothesis Testing", "Python", "Statistical Analysis"},
			ToolsAndTech:  []string{"Python", "NumPy", "Pandas", "SciPy", "Statistical Libraries"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    false,
		},
		{
			Title:         "Designer to Developer Handoff: Build a Project from a Design File",
			Description:   "Learn how to turn finished Figma designs into fully coded projects. Master the essential skills to bridge the gap between design and development, and bring creative visions to life with code.",
			Slug:          "designer-developer-handoff",
			URL:           "https://zerotomastery.io/courses/designer-to-developer-handoff/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/4ccXdWhFx7lsHuLhxN9SWB/ac1fa69b5f895b12b0345f382ef10ec7/Blue__49_.jpg",
			Instructor:    "Matt Studdert",
			Duration:      "3.5 Hours",
			LessonsCount:  33,
			Level:         "intermediate",
			Category:      "design",
			Price:         89.99,
			Rating:        4.6,
			StudentsCount: 6500,
			Prerequisites: []string{"Basic HTML/CSS", "Figma familiarity", "Web development basics"},
			WhatYouLearn:  []string{"Design handoff", "Figma to code", "Web development", "Design implementation"},
			Topics:        []string{"Figma", "Web Development", "Design Handoff", "Frontend Development"},
			ToolsAndTech:  []string{"Figma", "HTML", "CSS", "JavaScript", "Design Tools"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    false,
		},
		{
			Title:         "Complete Python Developer in 2026: Zero to Mastery",
			Description:   "Learn Python. Get hired. This is one of the most popular, highly rated python coding bootcamps online. It's also the most modern and up-to-date. Guaranteed. This is the only Python course you need if you want to go from complete Python beginner to getting hired as a Python Developer this year!",
			Slug:          "complete-python-developer-2026-updated",
			URL:           "https://zerotomastery.io/courses/learn-python/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/2wqtcZLn5BirJ42EDfoair/95be1804195bb47acb392cec54eb551b/Complete_Python_Developer_Zero_to_Mastery.jpg",
			Instructor:    "Andrei Neagoie",
			Duration:      "2 Months",
			LessonsCount:  350,
			Level:         "beginner",
			Category:      "programming",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 300000,
			Prerequisites: []string{"Basic computer skills", "No programming experience required"},
			WhatYouLearn:  []string{"Python programming", "Web development", "Data science", "Automation", "AI/ML basics"},
			Topics:        []string{"Python", "Programming", "Web Development", "Data Science", "Automation"},
			ToolsAndTech:  []string{"Python", "Django", "Flask", "NumPy", "Pandas", "Git"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "Prompt Engineering Bootcamp (Working With AI & LLMs): Zero to Mastery",
			Description:   "Stop memorizing random prompts. Instead, learn how AI & LLMs (Large Language Models) actually work and how to use them effectively. This course will take you from being a complete beginner to the forefront of the AI world.",
			Slug:          "prompt-engineering-bootcamp",
			URL:           "https://zerotomastery.io/courses/prompt-engineering-bootcamp/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/7XmCBS35kqsky2S2mtuoP/1f6b6aa94f921f14a833459d5ac8e82e/image.png",
			Instructor:    "Scott Kerr",
			Duration:      "24 Days",
			LessonsCount:  200,
			Level:         "intermediate",
			Category:      "ai",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 45000,
			Prerequisites: []string{"Basic understanding of AI concepts", "Computer literacy"},
			WhatYouLearn:  []string{"Prompt engineering", "AI & LLM fundamentals", "AI tool usage", "Autonomous agents"},
			Topics:        []string{"Prompt Engineering", "AI", "LLMs", "Machine Learning", "AI Tools"},
			ToolsAndTech:  []string{"ChatGPT", "Claude", "Gemini", "OpenAI API", "AI Platforms"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "The Vibe Coding Bootcamp: Become an AI-Augmented Developer",
			Description:   "Learn to focus on what really matters while coding with AI by using the latest tools including Cursor, Copilot, Claude, Gemini, ChatGPT, open source tools and more. Direct your vision, build real projects, and create a job-ready portfolio to launch your tech career fast.",
			Slug:          "vibe-coding-bootcamp",
			URL:           "https://zerotomastery.io/courses/learn-vibe-coding/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/395iMiqbPBUPQGGEluVUXT/ca0636cf2e4f182c5f5821386bcd02ee/Academy_3_Course_Thumbnail_-_Bash_Programming.png",
			Instructor:    "Jacinto Wong",
			Duration:      "20 Days",
			LessonsCount:  150,
			Level:         "intermediate",
			Category:      "development",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 25000,
			Prerequisites: []string{"Basic programming knowledge", "Understanding of development concepts"},
			WhatYouLearn:  []string{"AI-augmented development", "Cursor", "GitHub Copilot", "AI coding tools"},
			Topics:        []string{"AI Development", "Vibe Coding", "Cursor", "Copilot", "AI Tools"},
			ToolsAndTech:  []string{"Cursor", "GitHub Copilot", "Claude", "Gemini", "ChatGPT", "AI IDEs"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "The Complete Web Developer in 2026: Zero to Mastery",
			Description:   "Learn to code. Get hired. This is one of the most popular, highly rated coding bootcamps online. It's also the most modern and up-to-date. Guaranteed. You'll go from complete beginner to learning to code and getting hired as a Developer (this year!) at companies like Google, Tesla, and Amazon.",
			Slug:          "complete-web-developer-2026",
			URL:           "https://zerotomastery.io/courses/coding-bootcamp/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/34oTrOaPCY3VKnubPKZCKv/a8eb7d89a56594d9d5acb91252b451b5/MTCI.png",
			Instructor:    "Andrei Neagoie",
			Duration:      "3 Months",
			LessonsCount:  500,
			Level:         "beginner",
			Category:      "web-development",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 400000,
			Prerequisites: []string{"Basic computer skills", "No coding experience required"},
			WhatYouLearn:  []string{"HTML", "CSS", "JavaScript", "React", "Node.js", "Machine Learning basics"},
			Topics:        []string{"Web Development", "HTML", "CSS", "JavaScript", "React", "Node.js"},
			ToolsAndTech:  []string{"HTML", "CSS", "JavaScript", "React", "Node.js", "Git", "MongoDB"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "Complete Ethical Hacking Bootcamp: Zero to Mastery",
			Description:   "Become a security expert and get hired this year by learning Ethical Hacking & Penetration Testing from scratch. You'll learn by using real techniques used by black hat hackers and then learn how to defend against them.",
			Slug:          "complete-ethical-hacking-bootcamp",
			URL:           "https://zerotomastery.io/courses/learn-ethical-hacking/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/6pQ2cKjY6Lcus7FbiGjpNL/6ac6f5608a36aac3759e16b2edfff067/Course_Thumbnail_-_Advanced_Ethical_Hacking_-_final2.jpg",
			Instructor:    "Aleksa Tamburkovski, Andrei Neagoie",
			Duration:      "60 Days",
			LessonsCount:  300,
			Level:         "beginner",
			Category:      "cybersecurity",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 80000,
			Prerequisites: []string{"Basic computer skills", "Understanding of networks", "Linux basics helpful"},
			WhatYouLearn:  []string{"Ethical hacking", "Penetration testing", "Network security", "Security tools"},
			Topics:        []string{"Ethical Hacking", "Penetration Testing", "Network Security", "Cybersecurity"},
			ToolsAndTech:  []string{"Kali Linux", "Metasploit", "Nmap", "Wireshark", "Burp Suite"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "Complete A.I. Machine Learning and Data Science: Zero to Mastery",
			Description:   "One of the most popular, highly rated A.I., machine learning and data science bootcamps online. It's also the most modern and up-to-date. Guaranteed. You'll go from complete beginner with no prior experience to getting hired as a Machine Learning Engineer this year.",
			Slug:          "complete-ai-machine-learning-data-science",
			URL:           "https://zerotomastery.io/courses/machine-learning-and-data-science-bootcamp/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/1aWfPEIZchWyNbKoAi181o/43a1e23677077e353c4b2f83f8b25cb2/Course_Thumbnail_-_RAG_Bootcamp__5_.jpg",
			Instructor:    "Andrei Neagoie, Daniel Bourke",
			Duration:      "3 Months",
			LessonsCount:  400,
			Level:         "beginner",
			Category:      "ai",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 250000,
			Prerequisites: []string{"Basic computer skills", "Basic math helpful", "No programming experience required"},
			WhatYouLearn:  []string{"Machine Learning", "Data Science", "Python", "TensorFlow", "Pandas", "Data Analysis"},
			Topics:        []string{"Machine Learning", "Data Science", "Python", "TensorFlow", "Neural Networks"},
			ToolsAndTech:  []string{"Python", "TensorFlow", "Pandas", "NumPy", "Scikit-learn", "Jupyter"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "DevOps Bootcamp: Learn Linux & Become a Linux Sysadmin",
			Description:   "This DevOps Bootcamp will take you from an absolute beginner in Linux to getting hired as a confident and effective Linux System Administrator.",
			Slug:          "devops-bootcamp-linux-sysadmin",
			URL:           "https://zerotomastery.io/courses/devops-bootcamp/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/395iMiqbPBUPQGGEluVUXT/ca0636cf2e4f182c5f5821386bcd02ee/Academy_3_Course_Thumbnail_-_Bash_Programming.png",
			Instructor:    "Andrei Dumitrescu",
			Duration:      "32 Days",
			LessonsCount:  250,
			Level:         "beginner",
			Category:      "devops",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 60000,
			Prerequisites: []string{"Basic computer skills", "Command line familiarity helpful"},
			WhatYouLearn:  []string{"Linux administration", "DevOps fundamentals", "System administration", "Server management"},
			Topics:        []string{"Linux", "DevOps", "System Administration", "Server Management"},
			ToolsAndTech:  []string{"Linux", "Bash", "Docker", "Ansible", "Nginx", "Apache"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "Complete React Developer (w/ Redux, Hooks, GraphQL)",
			Description:   "Learn React.js from two industry experts. This is the only React JS bootcamp course you need to learn React, build advanced large-scale apps from scratch, and get hired as a React Developer this year.",
			Slug:          "complete-react-developer-redux-hooks-graphql",
			URL:           "https://zerotomastery.io/courses/learn-react/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/34oTrOaPCY3VKnubPKZCKv/a8eb7d89a56594d9d5acb91252b451b5/MTCI.png",
			Instructor:    "Andrei Neagoie, Yihua Zhang",
			Duration:      "45 Days",
			LessonsCount:  300,
			Level:         "intermediate",
			Category:      "web-development",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 150000,
			Prerequisites: []string{"HTML, CSS, JavaScript knowledge", "Understanding of web development"},
			WhatYouLearn:  []string{"React.js", "Redux", "React Hooks", "GraphQL", "Large-scale React apps"},
			Topics:        []string{"React", "Redux", "JavaScript", "Frontend Development", "Web Development"},
			ToolsAndTech:  []string{"React", "Redux", "JavaScript", "GraphQL", "CSS", "HTML"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "Complete Node.js Developer",
			Description:   "Learn Node.js from two industry experts. This is the only Node JS course you need to learn Node, build advanced large-scale apps from scratch, and get hired as a Backend Developer or Node JS Developer this year. Go from Zero to Node Mastery.",
			Slug:          "complete-nodejs-developer",
			URL:           "https://zerotomastery.io/courses/learn-node-js/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/2n1XBWfwVs3XyltFQ6ECzA/7c77783335cddcd14b40121417520d51/Course_Thumbnail_-_Business_Intelligence_with_Excel_-_Academy_2.png",
			Instructor:    "Adam Odziemkowski, Andrei Neagoie",
			Duration:      "50 Days",
			LessonsCount:  350,
			Level:         "intermediate",
			Category:      "web-development",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 120000,
			Prerequisites: []string{"JavaScript knowledge", "Understanding of web development"},
			WhatYouLearn:  []string{"Node.js", "Backend development", "APIs", "Database integration", "Server-side JavaScript"},
			Topics:        []string{"Node.js", "Backend Development", "JavaScript", "APIs", "Express.js"},
			ToolsAndTech:  []string{"Node.js", "Express.js", "MongoDB", "JavaScript", "REST APIs"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "Complete SQL + Databases Bootcamp",
			Description:   "This SQL Bootcamp will take you from complete beginner to a master of SQL, database management, and database design. You'll learn by using fun exercises and working with all database types to give you real-world experience. No prior experience needed.",
			Slug:          "complete-sql-databases-bootcamp",
			URL:           "https://zerotomastery.io/courses/sql-bootcamp/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/76EVNIyjQLoZBC3WcJHrO0/78f21c9e6ffd29cab9d543f266fa6c85/Blue.jpg",
			Instructor:    "Mo Binni, Andrei Neagoie",
			Duration:      "45 Days",
			LessonsCount:  280,
			Level:         "beginner",
			Category:      "database",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 90000,
			Prerequisites: []string{"Basic computer skills", "No database experience required"},
			WhatYouLearn:  []string{"SQL", "Database design", "Database management", "PostgreSQL", "MySQL"},
			Topics:        []string{"SQL", "Databases", "Database Design", "PostgreSQL", "MySQL", "Data Management"},
			ToolsAndTech:  []string{"SQL", "PostgreSQL", "MySQL", "SQLite", "Database Design"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "Machine Learning with Hugging Face Bootcamp: Zero to Mastery",
			Description:   "Learn to do Machine Learning using the Hugging Face ecosystem from scratch. This project-based course will teach you everything from training to deployment using Hugging Face. We'll start from the basics, learn real skills used by Machine Learning Engineers, and have fun along the way!",
			Slug:          "machine-learning-hugging-face-bootcamp",
			URL:           "https://zerotomastery.io/courses/machine-learning-with-hugging-face/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/1aWfPEIZchWyNbKoAi181o/43a1e23677077e353c4b2f83f8b25cb2/Course_Thumbnail_-_RAG_Bootcamp__5_.jpg",
			Instructor:    "Daniel Bourke",
			Duration:      "28 Days",
			LessonsCount:  200,
			Level:         "intermediate",
			Category:      "ai",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 35000,
			Prerequisites: []string{"Basic Python knowledge", "Understanding of ML fundamentals"},
			WhatYouLearn:  []string{"Hugging Face", "Transformers", "NLP", "Model deployment", "ML engineering"},
			Topics:        []string{"Hugging Face", "Machine Learning", "NLP", "Transformers", "MLOps"},
			ToolsAndTech:  []string{"Hugging Face", "Transformers", "PyTorch", "TensorFlow", "Gradio"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "PyTorch for Deep Learning Bootcamp: Zero to Mastery",
			Description:   "Learn PyTorch from scratch! This PyTorch course is your step-by-step guide to developing your own deep learning models using PyTorch. You'll learn Deep Learning with PyTorch by building a massive 3-part real-world milestone project. By the end, you'll have the skills and portfolio to get hired as a Deep Learning Engineer.",
			Slug:          "pytorch-deep-learning-bootcamp",
			URL:           "https://zerotomastery.io/courses/learn-pytorch/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/2wqtcZLn5BirJ42EDfoair/95be1804195bb47acb392cec54eb551b/Complete_Python_Developer_Zero_to_Mastery.jpg",
			Instructor:    "Daniel Bourke",
			Duration:      "50 Days",
			LessonsCount:  350,
			Level:         "intermediate",
			Category:      "ai",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 80000,
			Prerequisites: []string{"Python programming", "Basic ML concepts", "Math fundamentals"},
			WhatYouLearn:  []string{"PyTorch", "Deep Learning", "Neural Networks", "Computer Vision", "ML deployment"},
			Topics:        []string{"PyTorch", "Deep Learning", "Neural Networks", "Computer Vision", "Machine Learning"},
			ToolsAndTech:  []string{"PyTorch", "Python", "TensorBoard", "NumPy", "Matplotlib", "Pandas"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "Complete Cybersecurity Bootcamp: Zero to Mastery",
			Description:   "The Cybersecurity Bootcamp that will take you from ZERO to HIRED as a Cyber Security Engineer. You'll learn the latest best practices, techniques, and tools used for network security so that you can build a fortress for digital assets and prevent black hat hackers from penetrating your systems.",
			Slug:          "complete-cybersecurity-bootcamp",
			URL:           "https://zerotomastery.io/courses/learn-cybersecurity-bootcamp/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/6pQ2cKjY6Lcus7FbiGjpNL/6ac6f5608a36aac3759e16b2edfff067/Course_Thumbnail_-_Advanced_Ethical_Hacking_-_final2.jpg",
			Instructor:    "Aleksa Tamburkovski",
			Duration:      "30 Days",
			LessonsCount:  250,
			Level:         "beginner",
			Category:      "cybersecurity",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 70000,
			Prerequisites: []string{"Basic computer skills", "Understanding of networks", "Security interest"},
			WhatYouLearn:  []string{"Cybersecurity fundamentals", "Network security", "Security best practices", "Defense strategies"},
			Topics:        []string{"Cybersecurity", "Network Security", "Security Operations", "Defense", "Risk Management"},
			ToolsAndTech:  []string{"Security Tools", "Firewall", "IDS/IPS", "SIEM", "Security Monitoring"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "JavaScript: The Advanced Concepts",
			Description:   "Learn modern, advanced JavaScript concepts and practices to be in the top 10% JavaScript Developers this year. This Advanced JavaScript course is even used as reference material to study for some FAANG company interview processes.",
			Slug:          "advanced-javascript-concepts",
			URL:           "https://zerotomastery.io/courses/advanced-javascript-concepts/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/34oTrOaPCY3VKnubPKZCKv/a8eb7d89a56594d9d5acb91252b451b5/MTCI.png",
			Instructor:    "Andrei Neagoie",
			Duration:      "35 Days",
			LessonsCount:  180,
			Level:         "advanced",
			Category:      "programming",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 100000,
			Prerequisites: []string{"Strong JavaScript knowledge", "Understanding of programming concepts"},
			WhatYouLearn:  []string{"Advanced JavaScript", "Performance optimization", "Design patterns", "Interview preparation"},
			Topics:        []string{"JavaScript", "Advanced Programming", "Performance", "Design Patterns", "Interview Prep"},
			ToolsAndTech:  []string{"JavaScript", "Node.js", "Browser APIs", "Performance Tools", "Testing"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "The Complete Junior to Senior Web Developer Roadmap",
			Description:   "Step-by-step roadmap to go from Junior Developer to Senior Developer. You'll learn all the technical and non-technical skills you need to become a Senior Web Developer in 2026!",
			Slug:          "junior-to-senior-web-developer-roadmap",
			URL:           "https://zerotomastery.io/courses/junior-to-senior-web-developer-roadmap/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/2n1XBWfwVs3XyltFQ6ECzA/7c77783335cddcd14b40121417520d51/Course_Thumbnail_-_Business_Intelligence_with_Excel_-_Academy_2.png",
			Instructor:    "Andrei Neagoie",
			Duration:      "60 Days",
			LessonsCount:  300,
			Level:         "advanced",
			Category:      "career-development",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 85000,
			Prerequisites: []string{"Web development experience", "Understanding of full-stack concepts"},
			WhatYouLearn:  []string{"Senior development skills", "System design", "Leadership", "Technical architecture"},
			Topics:        []string{"Career Development", "Senior Development", "System Design", "Leadership", "Architecture"},
			ToolsAndTech:  []string{"Advanced JavaScript", "System Design", "Architecture", "Performance", "Security"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "TensorFlow for Deep Learning Bootcamp: Zero to Mastery",
			Description:   "Learn TensorFlow. Get Hired as a TensorFlow Developer. This course will take you from a total beginner to becoming a Deep Learning Expert.",
			Slug:          "tensorflow-deep-learning-bootcamp",
			URL:           "https://zerotomastery.io/courses/learn-tensorflow/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/1aWfPEIZchWyNbKoAi181o/43a1e23677077e353c4b2f83f8b25cb2/Course_Thumbnail_-_RAG_Bootcamp__5_.jpg",
			Instructor:    "Daniel Bourke",
			Duration:      "60 Days",
			LessonsCount:  400,
			Level:         "intermediate",
			Category:      "ai",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 75000,
			Prerequisites: []string{"Python programming", "Basic ML concepts", "Math fundamentals"},
			WhatYouLearn:  []string{"TensorFlow", "Deep Learning", "Neural Networks", "ML engineering", "Model deployment"},
			Topics:        []string{"TensorFlow", "Deep Learning", "Neural Networks", "Machine Learning", "MLOps"},
			ToolsAndTech:  []string{"TensorFlow", "Python", "Keras", "TensorBoard", "NumPy", "Pandas"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "The Python Automation Bootcamp: Zero to Mastery",
			Description:   "This course will turn you into an automation wizard that can automate away all the boring, annoying parts of your work and life. You'll learn by being hands-on and building 11 automation projects using Python and AI. All from scratch. No coding experience required.",
			Slug:          "python-automation-bootcamp",
			URL:           "https://zerotomastery.io/courses/learn-python-automation/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/2wqtcZLn5BirJ42EDfoair/95be1804195bb47acb392cec54eb551b/Complete_Python_Developer_Zero_to_Mastery.jpg",
			Instructor:    "Travis Cuzick",
			Duration:      "32 Days",
			LessonsCount:  220,
			Level:         "beginner",
			Category:      "automation",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 45000,
			Prerequisites: []string{"Basic computer skills", "No coding experience required"},
			WhatYouLearn:  []string{"Python automation", "Scripting", "AI automation", "Workflow automation", "Productivity tools"},
			Topics:        []string{"Python", "Automation", "Scripting", "Productivity", "AI Tools"},
			ToolsAndTech:  []string{"Python", "Automation Libraries", "AI APIs", "Scripting", "Productivity Tools"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "Rust Programming: The Complete Developer's Guide",
			Description:   "Learn the Rust programming language from scratch! Learn how to code and build your own real-world applications using Rust so that you can get hired this year. No previous programming or Rust experience needed.",
			Slug:          "rust-programming-complete-guide",
			URL:           "https://zerotomastery.io/courses/learn-rust/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/4ccXdWhFx7lsHuLhxN9SWB/ac1fa69b5f895b12b0345f382ef10ec7/Blue__49_.jpg",
			Instructor:    "Jayson Lennon",
			Duration:      "25 Days",
			LessonsCount:  180,
			Level:         "beginner",
			Category:      "programming",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 35000,
			Prerequisites: []string{"Basic computer skills", "No programming experience required"},
			WhatYouLearn:  []string{"Rust programming", "Systems programming", "Memory safety", "Performance optimization"},
			Topics:        []string{"Rust", "Systems Programming", "Memory Management", "Performance", "Type Safety"},
			ToolsAndTech:  []string{"Rust", "Cargo", "Rust Analyzer", "Systems Programming", "Memory Safety"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "Unity Bootcamp: 3D Game Development",
			Description:   "Learn Unity. Get Hired. This is the only Unity course you need to go from complete beginner (no coding experience) to coding your own 3D games and getting hired as a Game Developer this year!",
			Slug:          "unity-bootcamp-3d-game-development",
			URL:           "https://zerotomastery.io/courses/learn-unity-bootcamp/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/75XmCBS35kqsky2S2mtuoP/1f6b6aa94f921f14a833459d5ac8e82e/image.png",
			Instructor:    "Luis Ramirez Jr",
			Duration:      "38 Days",
			LessonsCount:  250,
			Level:         "beginner",
			Category:      "game-development",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 55000,
			Prerequisites: []string{"Basic computer skills", "No coding experience required"},
			WhatYouLearn:  []string{"Unity game development", "3D game design", "C# scripting", "Game mechanics", "Game deployment"},
			Topics:        []string{"Unity", "Game Development", "3D Graphics", "C#", "Game Design"},
			ToolsAndTech:  []string{"Unity", "C#", "3D Modeling", "Game Physics", "Unity Editor"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "Advanced CSS & JavaScript Projects",
			Description:   "Master CSS and JavaScript by building real-world projects like a quiz game, expense tracker, and podcast player. Learn responsive design, API integration, and deploying full-stack apps. Build your skills to create interactive web applications that get you hired!",
			Slug:          "advanced-css-javascript-projects",
			URL:           "https://zerotomastery.io/courses/front-end-projects/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/7XmCBS35kqsky2S2mtuoP/1f6b6aa94f921f14a833459d5ac8e82e/image.png",
			Instructor:    "Jacinto Wong",
			Duration:      "25 Days",
			LessonsCount:  150,
			Level:         "intermediate",
			Category:      "web-development",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 40000,
			Prerequisites: []string{"HTML, CSS, JavaScript basics", "Understanding of web development"},
			WhatYouLearn:  []string{"Advanced CSS", "JavaScript projects", "Responsive design", "API integration", "Frontend development"},
			Topics:        []string{"CSS", "JavaScript", "Frontend Projects", "Responsive Design", "Web Development"},
			ToolsAndTech:  []string{"CSS", "JavaScript", "HTML", "APIs", "Frontend Frameworks"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "The CSS Bootcamp: Zero to Mastery",
			Description:   "Learn everything from CSS basics to advanced CSS techniques by completing 100+ exercises and projects. You'll learn how to use CSS to create beautiful, responsive websites that wow users and employers. Become a CSS Pro and never create an ugly website again.",
			Slug:          "css-bootcamp-zero-to-mastery",
			URL:           "https://zerotomastery.io/courses/css-bootcamp/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/76EVNIyjQLoZBC3WcJHrO0/78f21c9e6ffd29cab9d543f266fa6c85/Blue.jpg",
			Instructor:    "Jacinto Wong",
			Duration:      "45 Days",
			LessonsCount:  280,
			Level:         "beginner",
			Category:      "web-development",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 65000,
			Prerequisites: []string{"Basic HTML knowledge", "No CSS experience required"},
			WhatYouLearn:  []string{"CSS fundamentals", "Advanced CSS", "Responsive design", "CSS animations", "Modern CSS"},
			Topics:        []string{"CSS", "Web Design", "Responsive Design", "CSS Grid", "Flexbox", "Animations"},
			ToolsAndTech:  []string{"CSS", "HTML", "CSS Grid", "Flexbox", "SASS", "CSS Animations"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "Java Programming Bootcamp: Zero to Mastery",
			Description:   "Learn Java from scratch with an industry expert. You'll learn Java programming fundamentals all the way to advanced skills and reinforce your learning with over 80 exercises and 18 quizzes. The only course you need to go from complete programming beginner to being able to get hired as a Backend Developer!",
			Slug:          "java-programming-bootcamp",
			URL:           "https://zerotomastery.io/courses/java-bootcamp/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/2n1XBWfwVs3XyltFQ6ECzA/7c77783335cddcd14b40121417520d51/Course_Thumbnail_-_Business_Intelligence_with_Excel_-_Academy_2.png",
			Instructor:    "Maaike van Putten",
			Duration:      "38 Days",
			LessonsCount:  300,
			Level:         "beginner",
			Category:      "programming",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 70000,
			Prerequisites: []string{"Basic computer skills", "No programming experience required"},
			WhatYouLearn:  []string{"Java programming", "Backend development", "Object-oriented programming", "Java ecosystem"},
			Topics:        []string{"Java", "Backend Development", "OOP", "Spring", "Java EE"},
			ToolsAndTech:  []string{"Java", "Spring Boot", "Maven", "JUnit", "IntelliJ IDEA"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "Three.js Bootcamp: Zero to Mastery",
			Description:   "Learn Three.js by building your own projects. Taught by an industry professional, this course covers everything from beginner to advanced topics. If you're a JavaScript developer who is serious about taking your coding skills and career to the next level by creating incredible interactive 3D experiences directly within a web browser, then this is the course for you.",
			Slug:          "threejs-bootcamp-zero-to-mastery",
			URL:           "https://zerotomastery.io/courses/learn-three-js/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/34oTrOaPCY3VKnubPKZCKv/a8eb7d89a56594d9d5acb91252b451b5/MTCI.png",
			Instructor:    "Jesse Zhou",
			Duration:      "30 Days",
			LessonsCount:  200,
			Level:         "intermediate",
			Category:      "web-development",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 25000,
			Prerequisites: []string{"JavaScript knowledge", "Understanding of 3D concepts", "Web development experience"},
			WhatYouLearn:  []string{"Three.js", "3D graphics", "WebGL", "3D animations", "Interactive 3D experiences"},
			Topics:        []string{"Three.js", "3D Graphics", "WebGL", "JavaScript", "3D Animation"},
			ToolsAndTech:  []string{"Three.js", "WebGL", "JavaScript", "3D Modeling", "Animation"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "Complete React Native Developer [with Hooks]",
			Description:   "The only React Native course you need to learn React Native, build large-scale React Native iOS + Android apps from scratch and get hired as a Mobile App Developer this year.",
			Slug:          "complete-react-native-developer-hooks",
			URL:           "https://zerotomastery.io/courses/learn-react-native/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/75XmCBS35kqsky2S2mtuoP/1f6b6aa94f921f14a833459d5ac8e82e/image.png",
			Instructor:    "Andrei Neagoie, Mo Binni",
			Duration:      "40 Days",
			LessonsCount:  280,
			Level:         "intermediate",
			Category:      "mobile-development",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 60000,
			Prerequisites: []string{"React knowledge", "JavaScript experience", "Understanding of mobile development"},
			WhatYouLearn:  []string{"React Native", "Mobile app development", "iOS development", "Android development", "Cross-platform apps"},
			Topics:        []string{"React Native", "Mobile Development", "iOS", "Android", "Cross-Platform"},
			ToolsAndTech:  []string{"React Native", "React", "JavaScript", "Expo", "Mobile APIs"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "Remix (React Router) Bootcamp: Zero to Mastery",
			Description:   "Learn Remix (React Router) by building your own full-stack project. Taught by an industry professional, this course covers everything from beginner to advanced topics. If you're a Developer who is serious about taking your coding skills and career to the next level by building better websites, then this is the course for you.",
			Slug:          "remix-react-router-bootcamp",
			URL:           "https://zerotomastery.io/courses/learn-remix-run/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/7XmCBS35kqsky2S2mtuoP/1f6b6aa94f921f14a833459d5ac8e82e/image.png",
			Instructor:    "Zach Taylor",
			Duration:      "34 Days",
			LessonsCount:  180,
			Level:         "intermediate",
			Category:      "web-development",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 20000,
			Prerequisites: []string{"React knowledge", "JavaScript experience", "Understanding of web frameworks"},
			WhatYouLearn:  []string{"Remix", "React Router", "Full-stack development", "Modern web frameworks", "Server-side rendering"},
			Topics:        []string{"Remix", "React Router", "Full-Stack", "Web Frameworks", "SSR"},
			ToolsAndTech:  []string{"Remix", "React", "TypeScript", "Node.js", "Web APIs"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "TypeScript Bootcamp: Zero to Mastery",
			Description:   "Learn TypeScript by building your own real-world applications. Taught by an industry professional, this course covers everything from beginner to advanced topics. If you're a JavaScript developer who is serious about taking your coding skills and career to the next level, then this is the course for you.",
			Slug:          "typescript-bootcamp-zero-to-mastery",
			URL:           "https://zerotomastery.io/courses/typescript-bootcamp/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/4ccXdWhFx7lsHuLhxN9SWB/ac1fa69b5f895b12b0345f382ef10ec7/Blue__49_.jpg",
			Instructor:    "Jayson Lennon",
			Duration:      "20 Days",
			LessonsCount:  150,
			Level:         "intermediate",
			Category:      "programming",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 45000,
			Prerequisites: []string{"JavaScript knowledge", "Understanding of programming concepts"},
			WhatYouLearn:  []string{"TypeScript", "Type-safe JavaScript", "Advanced TypeScript", "Type system", "TypeScript patterns"},
			Topics:        []string{"TypeScript", "JavaScript", "Type Safety", "Programming", "Web Development"},
			ToolsAndTech:  []string{"TypeScript", "JavaScript", "Node.js", "TypeScript Compiler", "Type Definitions"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "Django Bootcamp: Zero to Mastery",
			Description:   "Learn Django from scratch and from an industry expert by building real-world apps. You'll learn the fundamentals all the way to advanced skills so that you can go from complete beginner to being able to get hired as a Django Developer!",
			Slug:          "django-bootcamp-zero-to-mastery",
			URL:           "https://zerotomastery.io/courses/django-bootcamp/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/2wqtcZLn5BirJ42EDfoair/95be1804195bb47acb392cec54eb551b/Complete_Python_Developer_Zero_to_Mastery.jpg",
			Instructor:    "Dominic Vacchiano",
			Duration:      "20 Days",
			LessonsCount:  160,
			Level:         "intermediate",
			Category:      "web-development",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 35000,
			Prerequisites: []string{"Python knowledge", "Understanding of web development", "Basic database concepts"},
			WhatYouLearn:  []string{"Django", "Python web development", "Full-stack Django", "Django REST", "Web frameworks"},
			Topics:        []string{"Django", "Python", "Web Development", "Backend", "Full-Stack"},
			ToolsAndTech:  []string{"Django", "Python", "PostgreSQL", "Django REST", "Django Templates"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "Go Programming (Golang): The Complete Developer's Guide",
			Description:   "Learn Golang from scratch, from an industry expert by building real-world apps. You'll learn the Go fundamentals all the way to advanced concurrency so that you go from beginner to being able to get hired as a Go Developer!",
			Slug:          "go-programming-golang-complete-guide",
			URL:           "https://zerotomastery.io/courses/learn-golang/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/395iMiqbPBUPQGGEluVUXT/ca0636cf2e4f182c5f5821386bcd02ee/Academy_3_Course_Thumbnail_-_Bash_Programming.png",
			Instructor:    "Jayson Lennon",
			Duration:      "14 Days",
			LessonsCount:  120,
			Level:         "beginner",
			Category:      "programming",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 30000,
			Prerequisites: []string{"Basic programming knowledge", "Understanding of programming concepts"},
			WhatYouLearn:  []string{"Go programming", "Golang", "Concurrency", "Go fundamentals", "Systems programming"},
			Topics:        []string{"Go", "Golang", "Concurrency", "Systems Programming", "Backend Development"},
			ToolsAndTech:  []string{"Go", "Golang", "Go Modules", "Concurrency", "Systems Programming"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "Complete Angular Developer: Zero to Mastery",
			Description:   "Learn Angular from a senior industry professional. This is the only Angular course you need to learn Angular, build enterprise-level applications from scratch, and get hired as an Angular Developer.",
			Slug:          "complete-angular-developer-zero-to-mastery",
			URL:           "https://zerotomastery.io/courses/learn-angular/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/75XmCBS35kqsky2S2mtuoP/1f6b6aa94f921f14a833459d5ac8e82e/image.png",
			Instructor:    "Luis Ramirez Jr",
			Duration:      "40 Days",
			LessonsCount:  250,
			Level:         "intermediate",
			Category:      "web-development",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 45000,
			Prerequisites: []string{"JavaScript knowledge", "TypeScript understanding", "Web development experience"},
			WhatYouLearn:  []string{"Angular", "Enterprise applications", "TypeScript", "Frontend frameworks", "Web development"},
			Topics:        []string{"Angular", "TypeScript", "Frontend", "Web Development", "Enterprise Apps"},
			ToolsAndTech:  []string{"Angular", "TypeScript", "RxJS", "Node.js", "Angular CLI"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "Complete Vue Developer [Pinia, Vitest]",
			Description:   "The only Vue.js tutorial + projects course you need to learn Vue (including all new Vue 3 features), build large-scale Vue applications from scratch, and get hired as a Vue Developer this year.",
			Slug:          "complete-vue-developer-pinia-vitest",
			URL:           "https://zerotomastery.io/courses/learn-vue-js/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/34oTrOaPCY3VKnubPKZCKv/a8eb7d89a56594d9d5acb91252b451b5/MTCI.png",
			Instructor:    "Luis Ramirez Jr, Andrei Neagoie",
			Duration:      "30 Days",
			LessonsCount:  200,
			Level:         "intermediate",
			Category:      "web-development",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 40000,
			Prerequisites: []string{"JavaScript knowledge", "Understanding of web frameworks", "Frontend development experience"},
			WhatYouLearn:  []string{"Vue.js", "Vue 3", "Pinia", "Vitest", "Modern Vue development"},
			Topics:        []string{"Vue.js", "Frontend", "JavaScript", "Web Development", "Vue 3"},
			ToolsAndTech:  []string{"Vue.js", "Pinia", "Vitest", "JavaScript", "Vue Router"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "PHP Development Bootcamp: Zero to Mastery",
			Description:   "Learn modern PHP and become a better developer. This is the only PHP course you need to go from complete beginner to coding your own PHP applications and working with existing PHP applications.",
			Slug:          "php-development-bootcamp-zero-to-mastery",
			URL:           "https://zerotomastery.io/courses/learn-php-bootcamp/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/2n1XBWfwVs3XyltFQ6ECzA/7c77783335cddcd14b40121417520d51/Course_Thumbnail_-_Business_Intelligence_with_Excel_-_Academy_2.png",
			Instructor:    "Luis Ramirez Jr",
			Duration:      "42 Days",
			LessonsCount:  280,
			Level:         "beginner",
			Category:      "web-development",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 35000,
			Prerequisites: []string{"Basic computer skills", "Understanding of web concepts", "No PHP experience required"},
			WhatYouLearn:  []string{"PHP programming", "Modern PHP", "Web development", "Backend development", "PHP applications"},
			Topics:        []string{"PHP", "Web Development", "Backend", "Programming", "Modern PHP"},
			ToolsAndTech:  []string{"PHP", "Composer", "MySQL", "Laravel concepts", "Web Servers"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "Web Security & Bug Bounty: Learn Penetration Testing",
			Description:   "Start a career or earn a side income by becoming a Bug Bounty Hunter. No previous experience needed, we teach you everything from scratch. Hack websites, fix vulnerabilities, improve web security, and much more. You'll learn penetration testing from the very beginning and master the most modern pentesting tools and best practices!",
			Slug:          "web-security-bug-bounty-penetration-testing",
			URL:           "https://zerotomastery.io/courses/learn-penetration-testing/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/6pQ2cKjY6Lcus7FbiGjpNL/6ac6f5608a36aac3759e16b2edfff067/Course_Thumbnail_-_Advanced_Ethical_Hacking_-_final2.jpg",
			Instructor:    "Aleksa Tamburkovski, Andrei Neagoie",
			Duration:      "22 Days",
			LessonsCount:  150,
			Level:         "intermediate",
			Category:      "cybersecurity",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 25000,
			Prerequisites: []string{"Basic web knowledge", "Understanding of HTTP", "Security interest"},
			WhatYouLearn:  []string{"Penetration testing", "Bug bounty hunting", "Web security", "Vulnerability assessment", "Security tools"},
			Topics:        []string{"Penetration Testing", "Bug Bounty", "Web Security", "Cybersecurity", "Vulnerabilities"},
			ToolsAndTech:  []string{"Burp Suite", "Nmap", "OWASP Tools", "Security Testing", "Web Vulnerabilities"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "DevOps Bootcamp: Terraform",
			Description:   "Learn Terraform from scratch, from an industry expert. You'll learn Terraform fundamentals all the way to provisioning real-world cloud infrastructure on AWS so that you go from beginner to being able to get hired as a DevOps Engineer or System Administrator!",
			Slug:          "devops-bootcamp-terraform",
			URL:           "https://zerotomastery.io/courses/learn-terraform-certification/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/395iMiqbPBUPQGGEluVUXT/ca0636cf2e4f182c5f5821386bcd02ee/Academy_3_Course_Thumbnail_-_Bash_Programming.png",
			Instructor:    "Andrei Dumitrescu",
			Duration:      "20 Days",
			LessonsCount:  140,
			Level:         "intermediate",
			Category:      "devops",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 30000,
			Prerequisites: []string{"Cloud computing basics", "Understanding of infrastructure", "DevOps interest"},
			WhatYouLearn:  []string{"Terraform", "Infrastructure as Code", "AWS", "Cloud provisioning", "DevOps automation"},
			Topics:        []string{"Terraform", "DevOps", "AWS", "Infrastructure as Code", "Cloud Computing"},
			ToolsAndTech:  []string{"Terraform", "AWS", "CloudFormation", "DevOps Tools", "Infrastructure"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "Dart: The Complete Developer's Guide",
			Description:   "Learn Dart programming in depth from an actual Google Developer Expert. This is the only Dart tutorial + projects course you need to learn Dart and build real-world applications from scratch. Go from zero To Dart Mastery.",
			Slug:          "dart-complete-developers-guide",
			URL:           "https://zerotomastery.io/courses/learn-dart/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/4ccXdWhFx7lsHuLhxN9SWB/ac1fa69b5f895b12b0345f382ef10ec7/Blue__49_.jpg",
			Instructor:    "Andrea Bizzotto",
			Duration:      "30 Days",
			LessonsCount:  180,
			Level:         "beginner",
			Category:      "programming",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 20000,
			Prerequisites: []string{"Basic programming knowledge", "Understanding of programming concepts"},
			WhatYouLearn:  []string{"Dart programming", "Mobile development", "Flutter preparation", "Dart ecosystem", "Google Dart"},
			Topics:        []string{"Dart", "Programming", "Mobile Development", "Flutter", "Google Technologies"},
			ToolsAndTech:  []string{"Dart", "Flutter", "Dart SDK", "Mobile Development", "Programming"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
		{
			Title:         "Flutter Bootcamp: Zero to Mastery",
			Description:   "Learn Flutter from scratch with an industry expert. You'll learn Flutter programming fundamentals all the way to advanced skills and reinforce your skills by building a Twitter clone. The only course you need to go from complete Flutter beginner to being able to deploy your own iOS and Android apps and get hired as a Flutter Developer!",
			Slug:          "flutter-bootcamp-zero-to-mastery",
			URL:           "https://zerotomastery.io/courses/flutter-bootcamp/",
			Thumbnail:     "https://images.ctfassets.net/aq13lwl6616q/75XmCBS35kqsky2S2mtuoP/1f6b6aa94f921f14a833459d5ac8e82e/image.png",
			Instructor:    "Tadas Petra",
			Duration:      "30 Days",
			LessonsCount:  200,
			Level:         "beginner",
			Category:      "mobile-development",
			Price:         89.99,
			Rating:        4.9,
			StudentsCount: 40000,
			Prerequisites: []string{"Basic programming knowledge", "Understanding of mobile concepts", "Dart knowledge helpful"},
			WhatYouLearn:  []string{"Flutter", "Mobile app development", "iOS development", "Android development", "Cross-platform apps"},
			Topics:        []string{"Flutter", "Mobile Development", "iOS", "Android", "Cross-Platform"},
			ToolsAndTech:  []string{"Flutter", "Dart", "Mobile SDKs", "iOS Development", "Android Development"},
			IsZTMCourse:   true,
			IsActive:      true,
			IsFeatured:    true,
		},
	}

	for _, course := range ztmCourses {
		if err := db.Where("slug = ?", course.Slug).FirstOrCreate(&course).Error; err != nil {
			log.Printf("Failed to create course %s: %v", course.Title, err)
		}
	}

	// Create Learning Path to Course mappings
	learningPathCourses := []models.LearningPathCourse{
		// Python Programming Path
		{LearningPathID: 3, CourseID: 1, Order: 1, IsRequired: true, Notes: "Start with Python fundamentals", EstimatedWeeks: 12},

		// JavaScript Mastery Path
		{LearningPathID: 1, CourseID: 2, Order: 1, IsRequired: true, Notes: "Essential for coding interviews and problem solving", EstimatedWeeks: 6},

		// TypeScript Professional Development Path
		{LearningPathID: 2, CourseID: 2, Order: 1, IsRequired: true, Notes: "TypeScript builds on JavaScript fundamentals", EstimatedWeeks: 4},
		{LearningPathID: 2, CourseID: 12, Order: 2, IsRequired: false, Notes: "Improve productivity with advanced text editing", EstimatedWeeks: 2},

		// Java Enterprise Development Path
		{LearningPathID: 4, CourseID: 2, Order: 1, IsRequired: true, Notes: "Data structures and algorithms essential for Java", EstimatedWeeks: 6},

		// C# and .NET Development Path
		{LearningPathID: 5, CourseID: 2, Order: 1, IsRequired: true, Notes: "Programming fundamentals for C#", EstimatedWeeks: 6},

		// Rust Systems Programming Path
		{LearningPathID: 6, CourseID: 2, Order: 1, IsRequired: true, Notes: "Advanced algorithms for systems programming", EstimatedWeeks: 8},

		// C++ Game Development Path
		{LearningPathID: 7, CourseID: 2, Order: 1, IsRequired: true, Notes: "Critical for game development optimization", EstimatedWeeks: 8},

		// SQL Database Mastery Path
		{LearningPathID: 12, CourseID: 7, Order: 1, IsRequired: true, Notes: "Excel skills complement database work", EstimatedWeeks: 4},
		{LearningPathID: 12, CourseID: 11, Order: 2, IsRequired: true, Notes: "Statistics for data analysis", EstimatedWeeks: 6},

		// DevOps Engineering Path
		{LearningPathID: 13, CourseID: 6, Order: 1, IsRequired: true, Notes: "Fundamental for DevOps automation", EstimatedWeeks: 6},
		{LearningPathID: 13, CourseID: 12, Order: 2, IsRequired: false, Notes: "Advanced text editing for DevOps", EstimatedWeeks: 2},

		// Ethical Hacking Path
		{LearningPathID: 14, CourseID: 4, Order: 1, IsRequired: true, Notes: "Advanced network hacking techniques", EstimatedWeeks: 4},
		{LearningPathID: 14, CourseID: 5, Order: 2, IsRequired: true, Notes: "Foundation certification for cybersecurity", EstimatedWeeks: 5},

		// Network Security Path
		{LearningPathID: 15, CourseID: 5, Order: 1, IsRequired: true, Notes: "Essential security certification", EstimatedWeeks: 5},
		{LearningPathID: 15, CourseID: 4, Order: 2, IsRequired: false, Notes: "Advanced techniques for network security", EstimatedWeeks: 4},

		// Cloud Security Path
		{LearningPathID: 16, CourseID: 5, Order: 1, IsRequired: true, Notes: "Security fundamentals for cloud", EstimatedWeeks: 5},
		{LearningPathID: 16, CourseID: 4, Order: 2, IsRequired: false, Notes: "Advanced security techniques", EstimatedWeeks: 4},

		// Digital Forensics Path
		{LearningPathID: 17, CourseID: 5, Order: 1, IsRequired: true, Notes: "Security foundation for forensics", EstimatedWeeks: 5},
	}

	for _, lpc := range learningPathCourses {
		if err := db.Where("learning_path_id = ? AND course_id = ?", lpc.LearningPathID, lpc.CourseID).FirstOrCreate(&lpc).Error; err != nil {
			log.Printf("Failed to create learning path course mapping: %v", err)
		}
	}

	for _, lp := range learningPaths {
		if err := db.Where("title = ? AND creator_id = ?", lp.Title, lp.CreatorID).FirstOrCreate(&lp).Error; err != nil {
			log.Printf("Failed to create learning path %s: %v", lp.Title, err)
		}
	}

	log.Println("Demo data seeded successfully")
}
